parser: "babel-eslint"
rules:
  # Modifications to standard
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - never
  handle-callback-err: 0

env:
  es6: true
  node: true
  browser: true
extends: 'standard'
