parser: "babel-eslint"
env:
  es6: true
  node: true
  browser: true
extends: 'standard'

rules: # Modifications to standard
  indent:
    - 2
    - 2
  quotes:
    - 1
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 0
    - always
  handle-callback-err: 0
  space-before-function-paren: 0